<?php

namespace Database\Seeders;

use App\Models\Board;
use App\Models\BoardTemplate;
use Illuminate\Database\Seeder;

class BoardSeeder extends Seeder
{
    /**
     * 게시판 데이터를 시드합니다.
     */
    public function run(): void
    {
        // 템플릿 조회 (선택적으로 사용)
        $noticeTemplate = BoardTemplate::where('name', '공지사항')->first();
        $galleryTemplate = BoardTemplate::where('name', '갤러리')->first();
        $generalArchiveTemplate = BoardTemplate::where('name', '일반 자료실')->first();
        $academicArchiveTemplate = BoardTemplate::where('name', '학술 자료실')->first();
        $memberArchiveTemplate = BoardTemplate::where('name', '회원 자료실')->first();
        $academicJournalTemplate = BoardTemplate::where('name', '학술지')->first();
        $memberSquareNoticesTemplate = BoardTemplate::where('name', '학회 공지')->first();
        $otherNoticesTemplate = BoardTemplate::where('name', '기타 공지')->first();
        $memberSquareAlbumTemplate = BoardTemplate::where('name', '학회 앨범')->first();
        $inquiryQnaTemplate = BoardTemplate::where('name', 'Q&A')->first();
        $societyRulesTemplate = BoardTemplate::where('name', '회칙 관리')->first();
        $privacyPolicyTemplate = BoardTemplate::where('name', '개인정보처리방침')->first();
        $termsOfServiceTemplate = BoardTemplate::where('name', '이용약관')->first();
        $societyHistoryTemplate = BoardTemplate::where('name', '학회 연혁')->first();
        $committeeNoticeTemplate = BoardTemplate::where('name', '위원회 공지')->first();
        $academicNoticeTemplate = BoardTemplate::where('name', '학술대회 공지사항')->first();

        // 스킨 조회
        $defaultSkin = \App\Models\BoardSkin::where('name', '기본 스킨')->first();
        $gallerySkin = \App\Models\BoardSkin::where('name', '갤러리 스킨')->first();
        $historyYearOptions = implode(',', range((int) date('Y') + 5, 1950));
        $historyMonthOptions = implode(',', range(1, 12));

        $boards = [
            [
                'name' => '공지사항',
                'slug' => 'notices',
                'description' => '관리자가 작성하는 공지사항 게시판',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $noticeTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 15,
                'enable_notice' => true,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => false, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => true, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => null,
            ],
            [
                'name' => '갤러리',
                'slug' => 'gallerys',
                'description' => '썸네일 이미지를 보여주는 갤러리형 게시판',
                'skin_id' => $gallerySkin?->id,
                'template_id' => $galleryTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 12,
                'enable_notice' => true,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'member',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => true, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => true, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => true, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => true, 'required' => true, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => null,
            ],
            [
                'name' => '인사말',
                'slug' => 'greetings',
                'description' => '인사말 게시판',
                'skin_id' => $defaultSkin?->id,
                'template_id' => null,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 1,
                'enable_notice' => true,
                'is_single_page' => true,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => false, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => false, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => [
                    [
                        'name' => 'greeting_ko',
                        'type' => 'editor',
                        'label' => '인사말 국문',
                        'options' => null,
                        'required' => false,
                        'max_length' => null,
                        'placeholder' => null,
                    ],
                    [
                        'name' => 'greeting_en',
                        'type' => 'editor',
                        'label' => '인사말 영문',
                        'options' => null,
                        'required' => false,
                        'max_length' => null,
                        'placeholder' => null,
                    ],
                    [
                        'name' => 'ceo_message_ko',
                        'type' => 'text',
                        'label' => '대표이사 국문',
                        'options' => null,
                        'required' => false,
                        'max_length' => null,
                        'placeholder' => null,
                    ],
                    [
                        'name' => 'ceo_message_en',
                        'type' => 'text',
                        'label' => '대표이사 영문',
                        'options' => null,
                        'required' => false,
                        'max_length' => null,
                        'placeholder' => null,
                    ],
                ],
            ],
            [
                'name' => '학술 자료실',
                'slug' => 'academic_archive',
                'description' => '학술 자료실 게시판',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $academicArchiveTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 20,
                'enable_notice' => true,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => true, 'required' => true, 'label' => '게시글 분류'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => true, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => true, 'required' => true, 'label' => '공개여부'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => [
                    [
                        'name' => 'member_type',
                        'type' => 'checkbox',
                        'label' => '회원설정',
                        'options' => '준회원,정회원,평생회원,시니어회원',
                        'required' => false,
                        'max_length' => null,
                        'placeholder' => null,
                    ],
                    [
                        'name' => 'is_executive_public',
                        'type' => 'radio',
                        'label' => '임원공개여부',
                        'options' => 'all,executive',
                        'required' => true,
                        'max_length' => null,
                        'placeholder' => null,
                    ],
                ],
            ],
            [
                'name' => '일반 자료실',
                'slug' => 'general_archive',
                'description' => '일반 자료실 게시판',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $generalArchiveTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 20,
                'enable_notice' => true,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => true, 'required' => true, 'label' => '게시글 분류'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => true, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => true, 'required' => true, 'label' => '공개여부'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => [
                    [
                        'name' => 'member_type',
                        'type' => 'checkbox',
                        'label' => '회원설정',
                        'options' => '준회원,정회원,평생회원,시니어회원',
                        'required' => false,
                        'max_length' => null,
                        'placeholder' => null,
                    ],
                    [
                        'name' => 'is_executive_public',
                        'type' => 'radio',
                        'label' => '임원공개여부',
                        'options' => 'all,executive',
                        'required' => true,
                        'max_length' => null,
                        'placeholder' => null,
                    ],
                ],
            ],
            [
                'name' => '회원 자료실',
                'slug' => 'member_archive',
                'description' => '회원 자료실 게시판',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $memberArchiveTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 20,
                'enable_notice' => true,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => false, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => true, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => true, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => true, 'required' => true, 'label' => '공개여부'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => [
                    [
                        'name' => 'archive_type',
                        'type' => 'radio',
                        'label' => '자료 유형',
                        'options' => 'ebook,video,paper,guide',
                        'required' => true,
                        'max_length' => null,
                        'placeholder' => null,
                    ],
                    [
                        'name' => 'member_grade',
                        'type' => 'radio',
                        'label' => '회원 설정',
                        'options' => 'all,associate,regular,lifetime',
                        'required' => true,
                        'max_length' => null,
                        'placeholder' => null,
                    ],
                ],
            ],
            [
                'name' => '학술지',
                'slug' => 'academic_journals',
                'description' => '학회 자료실 학술지 링크 게시판',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $academicJournalTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 20,
                'enable_notice' => false,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => false, 'required' => false, 'label' => '내용'],
                    'category' => ['enabled' => false, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => true, 'required' => false, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => false, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => true, 'required' => true, 'label' => '공개여부'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => [
                    [
                        'name' => 'link_url',
                        'type' => 'url',
                        'label' => '링크 URL',
                        'options' => null,
                        'required' => true,
                        'max_length' => null,
                        'placeholder' => 'https://example.com',
                    ],
                ],
            ],
            [
                'name' => '학회 공지',
                'slug' => 'member_square_notices',
                'description' => '커뮤니티 학회 공지 게시판',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $memberSquareNoticesTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 20,
                'enable_notice' => true,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => false, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => true, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => true, 'required' => true, 'label' => '공개여부'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => null,
            ],
            [
                'name' => '기타 공지',
                'slug' => 'other_notices',
                'description' => '커뮤니티 기타 공지 게시판',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $otherNoticesTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 20,
                'enable_notice' => true,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => false, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => true, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => true, 'required' => true, 'label' => '공개여부'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => null,
            ],
            [
                'name' => '위원회 공지',
                'slug' => 'community_committee_notices',
                'description' => '커뮤니티 위원회별 공지 게시판',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $committeeNoticeTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 20,
                'enable_notice' => true,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'enable_comments' => false,
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => true, 'required' => true, 'label' => '위원회'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => true, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => true, 'required' => true, 'label' => '공개여부'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => null,
            ],
            [
                'name' => '위원회 토론장',
                'slug' => 'community_committee_discussions',
                'description' => '위원회별 토론 주제 게시판(댓글 사용)',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $committeeNoticeTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 20,
                'enable_notice' => true,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'enable_comments' => true,
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => true, 'required' => true, 'label' => '위원회'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => true, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => true, 'required' => true, 'label' => '공개여부'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => null,
            ],
            [
                'name' => '위원회 자료실',
                'slug' => 'community_committee_archive',
                'description' => '위원회별 자료실 게시판',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $committeeNoticeTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 20,
                'enable_notice' => true,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'enable_comments' => false,
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => true, 'required' => true, 'label' => '위원회'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => true, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => true, 'required' => true, 'label' => '공개여부'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => null,
            ],
            [
                'name' => '학회 앨범',
                'slug' => 'member_square_album',
                'description' => '커뮤니티 학회 앨범 게시판',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $memberSquareAlbumTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 20,
                'enable_notice' => false,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => false, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => true, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => true, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => true, 'required' => true, 'label' => '공개여부'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => null,
            ],
            [
                'name' => 'Q&A 관리',
                'slug' => 'inquiry_qna',
                'description' => '문의사항 Q&A 게시판',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $inquiryQnaTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 20,
                'enable_notice' => true,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => false, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => true, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => true, 'required' => true, 'label' => '공개여부'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => null,
            ],
            [
                'name' => '회칙 관리',
                'slug' => 'society_rules',
                'description' => '홈페이지 회칙 관리',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $societyRulesTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 1,
                'enable_notice' => false,
                'is_single_page' => true,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '타이틀'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '회칙 내용'],
                    'category' => ['enabled' => false, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => false, 'required' => false, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => false, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => false, 'required' => false, 'label' => '공개여부'],
                    'created_at' => ['enabled' => false, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => null,
            ],
            [
                'name' => '개인정보처리방침',
                'slug' => 'privacy_policy',
                'description' => '홈페이지 개인정보처리방침 관리',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $privacyPolicyTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 1,
                'enable_notice' => false,
                'is_single_page' => true,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '타이틀'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '개인정보처리방침'],
                    'category' => ['enabled' => false, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => false, 'required' => false, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => false, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => false, 'required' => false, 'label' => '공개여부'],
                    'created_at' => ['enabled' => false, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => null,
            ],
            [
                'name' => '이용약관',
                'slug' => 'terms_of_service',
                'description' => '홈페이지 이용약관 관리',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $termsOfServiceTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 1,
                'enable_notice' => false,
                'is_single_page' => true,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '타이틀'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '이용약관'],
                    'category' => ['enabled' => false, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => false, 'required' => false, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => false, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => false, 'required' => false, 'label' => '공개여부'],
                    'created_at' => ['enabled' => false, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => null,
            ],
            [
                'name' => '학술대회 공지사항',
                'slug' => 'academic_notices',
                'description' => '학술대회별 공지사항 게시판',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $academicNoticeTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 20,
                'enable_notice' => true,
                'is_single_page' => false,
                'enable_sorting' => false,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'enable_comments' => false,
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '제목'],
                    'content' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'category' => ['enabled' => false, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => true, 'required' => true, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => true, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => true, 'required' => true, 'label' => '공개여부'],
                    'created_at' => ['enabled' => true, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => null,
            ],
            [
                'name' => '학회 연혁',
                'slug' => 'society_history',
                'description' => '홈페이지 학회 연혁 관리',
                'skin_id' => $defaultSkin?->id,
                'template_id' => $societyHistoryTemplate?->id,
                'is_active' => true,
                'table_created' => false,
                'list_count' => 20,
                'enable_notice' => false,
                'is_single_page' => false,
                'enable_sorting' => true,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'admin',
                'permission_comment' => 'member',
                'field_config' => [
                    'title' => ['enabled' => true, 'required' => true, 'label' => '내용'],
                    'content' => ['enabled' => true, 'required' => false, 'label' => '상세 내용'],
                    'category' => ['enabled' => false, 'required' => false, 'label' => '카테고리'],
                    'author_name' => ['enabled' => false, 'required' => false, 'label' => '작성자'],
                    'password' => ['enabled' => false, 'required' => false, 'label' => '비밀번호'],
                    'attachments' => ['enabled' => false, 'required' => false, 'label' => '첨부파일'],
                    'thumbnail' => ['enabled' => false, 'required' => false, 'label' => '썸네일'],
                    'is_secret' => ['enabled' => false, 'required' => false, 'label' => '비밀글'],
                    'is_active' => ['enabled' => true, 'required' => true, 'label' => '사용여부'],
                    'created_at' => ['enabled' => false, 'required' => false, 'label' => '등록일'],
                ],
                'custom_fields_config' => [
                    [
                        'name' => 'history_year',
                        'type' => 'select',
                        'label' => '연도',
                        'options' => $historyYearOptions,
                        'required' => true,
                        'max_length' => null,
                        'placeholder' => null,
                    ],
                    [
                        'name' => 'history_month',
                        'type' => 'select',
                        'label' => '월',
                        'options' => $historyMonthOptions,
                        'required' => true,
                        'max_length' => null,
                        'placeholder' => null,
                    ],
                ],
            ],
        ];

        foreach ($boards as $board) {
            $boardModel = Board::withTrashed()->updateOrCreate(
                ['slug' => $board['slug']],
                $board
            );

            if ($boardModel->trashed()) {
                $boardModel->restore();
            }
        }

        Board::where('slug', 'annual_schedule')->delete();
    }
}
